[[pages]]
path = "/"
screenshotTimestamp = "2026-04-14T11:46:07Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/572b669f-6bc9-4149-ad5b-07d6b1ad80cd/605af9e0-2c4c-4a40-8589-fb0587970ca1/o2cG5UF"

[[pages]]
path = "/now"
screenshotTimestamp = "2026-04-13T18:21:56Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/572b669f-6bc9-4149-ad5b-07d6b1ad80cd/605af9e0-2c4c-4a40-8589-fb0587970ca1/hQNkQ2A"

[[pages]]
path = "/eats"
screenshotTimestamp = "2026-04-13T16:42:58Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/572b669f-6bc9-4149-ad5b-07d6b1ad80cd/605af9e0-2c4c-4a40-8589-fb0587970ca1/yBukjCe"

[[pages]]
path = "/book"
screenshotTimestamp = "2026-04-13T16:43:00Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/572b669f-6bc9-4149-ad5b-07d6b1ad80cd/605af9e0-2c4c-4a40-8589-fb0587970ca1/Nldx8pv"

[[pages]]
path = "/offers"
screenshotTimestamp = "2026-04-13T16:43:03Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/572b669f-6bc9-4149-ad5b-07d6b1ad80cd/605af9e0-2c4c-4a40-8589-fb0587970ca1/uVzokSX"

[[pages]]
path = "/privacy"
screenshotTimestamp = "2026-04-12T19:30:34Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/f09ac302-c0ba-46c0-b02d-193a8277c757/87436c3c-914a-4ec4-9cbd-8e25d373918b/fcACrN5"

[[pages]]
path = "/about"
screenshotTimestamp = "2026-04-12T19:30:29Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/f09ac302-c0ba-46c0-b02d-193a8277c757/87436c3c-914a-4ec4-9cbd-8e25d373918b/X3cDugM"

[[pages]]
path = "/contact"
screenshotTimestamp = "2026-04-12T19:30:32Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/f09ac302-c0ba-46c0-b02d-193a8277c757/87436c3c-914a-4ec4-9cbd-8e25d373918b/Me74YCl"

[[pages]]
path = "/#waitlist"
screenshotTimestamp = "2026-04-12T14:51:48Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/f09ac302-c0ba-46c0-b02d-193a8277c757/87436c3c-914a-4ec4-9cbd-8e25d373918b/pvkl6ch"

[[pages]]
path = "/merchant-setup"
screenshotTimestamp = "2026-04-13T19:55:56Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/572b669f-6bc9-4149-ad5b-07d6b1ad80cd/605af9e0-2c4c-4a40-8589-fb0587970ca1/cSDAF6x"

[[pages]]
path = "/delivery-setup"
screenshotTimestamp = "2026-04-13T20:04:16Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/572b669f-6bc9-4149-ad5b-07d6b1ad80cd/605af9e0-2c4c-4a40-8589-fb0587970ca1/h6So7Q4"

[[pages]]
path = "/restaurant-setup"
screenshotTimestamp = "2026-04-13T19:56:56Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/572b669f-6bc9-4149-ad5b-07d6b1ad80cd/605af9e0-2c4c-4a40-8589-fb0587970ca1/Q3Gxn0J"

[[pages]]
path = "/splash-video"
screenshotTimestamp = "2026-04-12T18:49:00Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/f09ac302-c0ba-46c0-b02d-193a8277c757/87436c3c-914a-4ec4-9cbd-8e25d373918b/od7F9fG"

[[pages]]
path = "/light"
screenshotTimestamp = "2026-04-12T15:27:12Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/f09ac302-c0ba-46c0-b02d-193a8277c757/87436c3c-914a-4ec4-9cbd-8e25d373918b/Iex6PZJ"

[[pages]]
path = "/#dual-hero"
screenshotTimestamp = "2026-04-12T15:52:23Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/f09ac302-c0ba-46c0-b02d-193a8277c757/87436c3c-914a-4ec4-9cbd-8e25d373918b/GV4VUhd"

[[pages]]
path = "/blog"
screenshotTimestamp = "2026-04-12T19:44:48Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/572b669f-6bc9-4149-ad5b-07d6b1ad80cd/605af9e0-2c4c-4a40-8589-fb0587970ca1/Ex8GRZ2"

[[pages]]
path = "/investors"
screenshotTimestamp = "2026-04-12T19:30:27Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/f09ac302-c0ba-46c0-b02d-193a8277c757/87436c3c-914a-4ec4-9cbd-8e25d373918b/XaqkgzB"

[[pages]]
path = "/terms"
screenshotTimestamp = "2026-04-12T19:30:36Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/f09ac302-c0ba-46c0-b02d-193a8277c757/87436c3c-914a-4ec4-9cbd-8e25d373918b/Gmucy4l"

[[pages]]
path = "/shop"
screenshotTimestamp = "2026-04-12T19:44:45Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/572b669f-6bc9-4149-ad5b-07d6b1ad80cd/605af9e0-2c4c-4a40-8589-fb0587970ca1/CxVjhs5"

[[pages]]
path = "/kirana-map"
screenshotTimestamp = "2026-04-13T16:43:16Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/572b669f-6bc9-4149-ad5b-07d6b1ad80cd/605af9e0-2c4c-4a40-8589-fb0587970ca1/MGD8QHY"

[[pages]]
path = "/app"
screenshotTimestamp = "2026-04-13T16:50:26Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/572b669f-6bc9-4149-ad5b-07d6b1ad80cd/605af9e0-2c4c-4a40-8589-fb0587970ca1/CVVxSyw"

[[pages]]
path = "/#app-download"
screenshotTimestamp = "2026-04-13T16:58:14Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/572b669f-6bc9-4149-ad5b-07d6b1ad80cd/605af9e0-2c4c-4a40-8589-fb0587970ca1/0k6PzC0"

[[pages]]
path = "/account"
screenshotTimestamp = "2026-04-13T18:15:29Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/572b669f-6bc9-4149-ad5b-07d6b1ad80cd/605af9e0-2c4c-4a40-8589-fb0587970ca1/sVavwGc"

[[pages]]
path = "/favicon.svg"
screenshotTimestamp = "2026-04-13T21:03:19Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/572b669f-6bc9-4149-ad5b-07d6b1ad80cd/605af9e0-2c4c-4a40-8589-fb0587970ca1/Y3dFw4o"
